### ISSUE TITLE
Symbols are not displayed 

### ISSUE THREAD

**Issue by Rak1ta** [Sussy-OS/LRA-Community-Edition#7]
Symbols are not displayed, the language changed to English, it did not help.
Did a clean install of Buster - no symbols.

RaspiOS 32bit Debian10

![Безымянный](https://user-images.githubusercontent.com/88277343/170945784-e95b9234-af4c-415f-a523-3e729d26cbbe.png)

**Comment by Sussy-OS** [comment]
Yes, benpi has noticed this. I have to take a look.

**Comment by Sussy-OS** [comment]
I have not encountered this though.

**Comment by Sussy-OS** [comment]
Until I fix this, run 
```
rm -rf LineRider && mkdir LineRider && cd LineRider && wget -O linerider.zip "https://github.com/Sussy-OS/LRA-Community-Edition/releases/download/2022.5.1/LineRider.game.auto-release.2022.5.1-LR.zip" && unzip linerider.zip && rm linerider.zip
```
to temperarorly fix this glitch.
If it asks to update, do not update. I will inform you when I have fixed this glitch.

**Comment by Sussy-OS** [comment]
I have also noticed that only on buster this glitch accurs.

**Comment by Sussy-OS** [comment]
Sorry for the late fix, @Rak1ta . :( We have the fix, but I do not have a Buster VM or SD Card, so can I test it out on your system? Also- do you have discord? That is more secure, as GitHub is open chat, so everyone would see your remote connect keys if you share them here. - rb24

**Comment by Rak1ta** [comment]
@Sussy-OS rb24#4590 - it's you?

**Comment by Sussy-OS** [comment]
No, I'm rb24#0032

**Comment by Sussy-OS** [comment]
Closing as pending merge of fix: https://github.com/Botspot/pi-apps/pull/2052
